import "./globals.css";
import Navbar from "./_(Component)/Navbar";
import ReduxProvider from "./_redux/ReduxProvider";
import Footer from "./_(Component)/Footer";
import EditBar from "./_(Component)/EditBar";
import AuthProvider from "./_context/AuthContext";
import { baseUrl } from "./page";
import axios from "axios";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbarThunk = async () => {
  try {
    const url = baseUrl('navbars');
    const response = await axios.get(url, {
      headers: {
        'Content-Type': 'application/json'
      }
    });
    return response.data.data

  } catch (error) {
    console.log(error)
  }
}

export default async function RootLayout({ children }) {
  const navBarData = await navbarThunk()
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <div>
              <EditBar />
              <Navbar test={navBarData} />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ReduxProvider>
        <script src="https://kit.fontawesome.com/ca347752a7.js" crossOrigin="anonymous"></script>
      </body>
    </html >
  );
}